name: "CSML Studio Sync"
description: "Easily synchronize and version your CSML Studio Chatbot from a Github repository."
author: "Clevy.io"
inputs:
  update:
    description: "Update the bot on CSML Studio with the contents of repo"
    required: false
  build:
    description: "Create a new build with the saved content on CSML Studio"
    required: false
  create-snapshot:
    description: "Create or update a chatbot snapshot on CSML Studio. Uses the tag as its name."
    required: false
  delete-snapshot:
    description: "Delete an existing snapshot with the current tag name"
    required: false
runs:
  using: "node12"
  main: "index.js"
