name: Save bot example

on:
  push:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:12.4-alpine

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        working-directory: .

      - name: CSML - Syncronize your repository with a bot on csml studio
        uses: mdarriga/csml-bot-sync-action@v18
        with:
          save: true
          build: true
        env:
          CSML_CLIENT_URL: https://md-api-clients.ngrok.io
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
