name: Save bot example

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync with studio
        uses: CSML-by-Clevy/csml-studio-sync-action
        with:
          update: true
          build: true
        env:
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}

      - name: Create new snapshot
        uses: CSML-by-Clevy/csml-studio-sync-action
        with:
          create-snapshot: true
        env:
          CSML_CLIENT_API_KEY: ${{ secrets.CSML_CLIENT_API_KEY }}
          CSML_CLIENT_API_SECRET: ${{ secrets.CSML_CLIENT_API_SECRET }}
